server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auberge
    password: auberge
    username: auberge
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect